# generated by maixhub, tested on maixpy3 v0.4.8
# copy files to TF card and plug into board and power on
import sensor
import KPU as kpu
from machine import UART
from fpioa_manager import fm
from modules import ws2812
from time import sleep

def blink(c, dt=0.5):
    led.set_led(0, c)
    led.display()
    sleep(dt)
    led.set_led(0, blk)
    led.display()

def send_detect_result(objects):

    idx, pmax = 0, 0
    for obj in objects:
        if obj.value() > pmax:
#            pos = obj.rect() # rect pos pos[0],.. pos[3]
            pmax = obj.value()
            idx  = obj.classid()
    u.write("{:3.2f} {}\n".format(pmax, labels[idx]))
    blink(v)

#
input_size = (224, 224)
labels = ['vit_30', 'ceder_pass', 'stat_int', 'sens_unique', 'pass_pieton', 'gyratoire', 'intersection', 'stop']
anchors = [4.62, 4.59, 4.41, 4.25, 3.47, 3.53, 4.0, 3.94, 5.0, 5.09]

# init uart
fm.register(34, fm.fpioa.UART1_TX, force=True)
fm.register(35, fm.fpioa.UART1_RX, force=True)
u = UART(UART.UART1, 115200)

# init rgb led
led = ws2812(8,100)
r, j, v, b, vi, blk = (250, 0, 0), (200, 32, 0), (0, 128, 0),(0, 0, 250), (128, 0, 128), (0, 0, 0)
leds = (r, j, v, b, vi)

# init sensor
sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.set_windowing(input_size)
sensor.run(1)

# init yolo2
task = kpu.load(0x300000)
kpu.init_yolo2(task, 0.5, 0.3, 5, anchors) # threshold:[0,1], nms_value: [0, 1]

#
blink(b, 1)

# main loop
while True:
    try:
        cmd = u.read()
        if cmd == b'record':
            img = sensor.snapshot()
            objects = kpu.run_yolo2(task, img)
            if objects:
                send_detect_result(objects)
            else:
                u.write("*************\n")
    except:
        u.write("detect. error\n")
